<?php

namespace Pdazcom\Referrals\Tests\Unit\Traits;

use Pdazcom\Referrals\Events\UserReferred;
use Pdazcom\Referrals\Models\ReferralLink;
use Pdazcom\Referrals\Models\ReferralProgram;
use Pdazcom\Referrals\Models\ReferralRelationship;
use Pdazcom\Referrals\Tests\TestCase;
use Pdazcom\Referrals\Tests\WithLoadMigrations;
use Illuminate\Support\Facades\Event;

class ReferralsMemberCodeAttributionTest extends TestCase
{
    use WithLoadMigrations;

    private ReferralProgram $program;

    protected function setUp(): void
    {
        parent::setUp();

        $this->program = ReferralProgram::create([
            'name' => 'example',
            'title' => 'Test Program',
            'description' => 'Test description',
            'uri' => 'test',
        ]);
    }

    public function testRegisterWithHumanFriendlyCode(): void
    {
        $referrer = $this->user();
        $newUser = $this->user();

        $link = $this->program->links()->create([
            'user_id' => $referrer->id,
            'referral_code' => 'INVITE2024',
        ]);

        $result = $newUser->registerWithCode('INVITE2024');

        $this->assertTrue($result);
        $this->assertCount(1, $link->relationships()->get());
        $this->assertEquals($newUser->id, $link->relationships()->first()->user_id);
    }

    public function testRegisterWithUuidCode(): void
    {
        $referrer = $this->user();
        $newUser = $this->user();

        $link = $this->program->links()->create([
            'user_id' => $referrer->id,
        ]);

        $result = $newUser->registerWithCode($link->code);

        $this->assertTrue($result);
        $this->assertCount(1, $link->relationships()->get());
        $this->assertEquals($newUser->id, $link->relationships()->first()->user_id);
    }

    public function testRegisterWithUnknownCodeReturnsFalse(): void
    {
        $newUser = $this->user();

        $result = $newUser->registerWithCode('DOESNOTEXIST');

        $this->assertFalse($result);
        $this->assertEquals(0, ReferralRelationship::count());
    }

    public function testRegisterWithCodeFiresUserReferredEvent(): void
    {
        Event::fake([UserReferred::class]);

        $referrer = $this->user();
        $newUser = $this->user();

        $link = $this->program->links()->create([
            'user_id' => $referrer->id,
            'referral_code' => 'WELCOME50',
        ]);

        $newUser->registerWithCode('WELCOME50');

        Event::assertDispatched(UserReferred::class, function (UserReferred $event) use ($link, $newUser) {
            return in_array($link->id, $event->referralIDs)
                && $event->user->id === $newUser->id;
        });
    }

    public function testRegisterWithCodeDoesNotDuplicateRelationship(): void
    {
        $referrer = $this->user();
        $newUser = $this->user();

        $link = $this->program->links()->create([
            'user_id' => $referrer->id,
            'referral_code' => 'ONCE-ONLY',
        ]);

        $newUser->registerWithCode('ONCE-ONLY');
        $newUser->registerWithCode('ONCE-ONLY');

        $this->assertEquals(1, $link->relationships()->count());
    }

    public function testLinkBasedAttributionContinuesToWork(): void
    {
        $referrer = $this->user();
        $newUser = $this->user();

        $link = $this->program->links()->create([
            'user_id' => $referrer->id,
        ]);

        $link->relationships()->firstOrCreate(['user_id' => $newUser->id]);

        $this->assertCount(1, $link->relationships()->get());
        $this->assertEquals($newUser->id, $link->relationships()->first()->user_id);
    }

    public function testRegisterWithAutoGeneratedReferralCode(): void
    {
        $referrer = $this->user();
        $newUser = $this->user();

        $link = $this->program->links()->create([
            'user_id' => $referrer->id,
        ]);

        $autoCode = $link->referral_code;
        $this->assertNotNull($autoCode);

        $result = $newUser->registerWithCode($autoCode);

        $this->assertTrue($result);
        $this->assertCount(1, $link->relationships()->get());
    }
}
